name: Docker Image CI

on:
  push:
    branches: 
      - 'ubuntu'
  pull_request:
    branches:
      - 'ubuntu'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Tencent Container Registry
        uses: docker/login-action@v1
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TC_DOCKER_USERNAME }}
          password: ${{ secrets.TC_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
              hewenyulucky/vscode
              ccr.ccs.tencentyun.com/hewenyulucky/vscode
          tags: |
              type=ref,event=branch
              type=sha,prefix={{branch}}-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
              ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
